name: "limgo-badge-action"
description: "Do not let your test coverage drop"
branding:
  color: orange
  icon: check-circle
inputs:
  limgo_file:
    description: "The limgo output to generate the badge for."
    required: true
  limgo_file_format:
    description: "The format of the limgo output. Has to be one of [tab, md, json]."
    required: false
    default: "tab"
  badge_name:
    description: "The name of the generated badge."
    required: false
    default: "limgo-badge.png"
  badge_enabled_stmt:
    description: "Flag to enable or disable the statement coverage being displayed in the generated badge."
    required: false
    default: "true"
  badge_enabled_lines:
    description: "Flag to enable or disable the lines coverage being displayed in the generated badge."
    required: false
    default: "true"
  badge_enabled_branch:
    description: "Flag to enable or disable the branch coverage being displayed in the generated badge."
    required: false
    default: "true"
  repo:
    description: "The repo to push the generated limgo badge to."
    required: true
  branch:
    description: "The branch to push the generated limgo badge to."
    required: false
    default: "limgo-badge"
  github_token:
    description: "The GitHub token to push to the current repo. Suggested as secrets.GITHUB_TOKEN"
    required: true
  github_token_owner:
    description: "The owner of the GitHub token."
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
